In [2]:
import sqlite3
import csv
import pandas as pd
import os
import re

import math
from tqdm import tqdm
import multiprocessing as mp
import time
import sched
import ast
import numpy as np
import os

folder_prefix = '/home/jovyan/work/'


In [3]:
full_250_df = pd.read_pickle(folder_prefix + "charters_full_2015_15_250.pkl")


In [4]:
full_250_df

CMO_NAME  CMO_MEMSUM  \
0                                      AAEC      1320.0   
1      Arizona Agribusiness & Equine Center      1320.0   
2                                      AAEC      1320.0   
3      Arizona Agribusiness & Equine Center      1320.0   
4                                      AAEC      1320.0   
5      Arizona Agribusiness & Equine Center      1320.0   
6           ACADEMY OF SKILLS AND KNOWLEDGE      1161.0   
7           ACADEMY OF SKILLS AND KNOWLEDGE      1161.0   
8           ACADEMY OF SKILLS AND KNOWLEDGE      1161.0   
9          ACCELERATED INTERMEDIATE ACADEMY       281.0   
10         ACCELERATED INTERMEDIATE ACADEMY       281.0   
11         ACCELERATED INTERMEDIATE ACADEMY       281.0   
12         ACCELERATED INTERMEDIATE ACADEMY       281.0   
13               ACE Public Charter Schools       953.0   
14               ACE Public Charter Schools       953.0   
15               ACE Public Charter Schools       953.0   
16               ACE Public Charter Schools       953.0   
17          ARISTOI CLASSICAL ACADEMY, INC.       644.0   
18          ARISTOI CLASSICAL ACADEMY, INC.       644.0   
19               ARLINGTON CLASSICS ACADEMY      1442.0   
20               ARLINGTON CLASSICS ACADEMY      1442.0   
21               ARLINGTON CLASSICS ACADEMY      1442.0   
22                             ASPIRA of PA      3966.0   
23      OmniVest Properties Management, LLC      7075.0   
24                             ASPIRA of PA      3966.0   
25      OmniVest Properties Management, LLC      7075.0   
26                             ASPIRA of PA      3966.0   
27                             ASPIRA of PA      3966.0   
28                             ASPIRA of PA      3966.0   
29                                Academica     48541.0   
...                                     ...         ...   
11491                                   NaN         NaN   
11492                                   NaN         NaN   
11493                                   NaN         NaN   
11494                                   NaN         NaN   
11495                                   NaN         NaN   
11496                                   NaN         NaN   
11497                                   NaN         NaN   
11498                                   NaN         NaN   
11499                                   NaN         NaN   
11500                                   NaN         NaN   
11501                                   NaN         NaN   
11502                                   NaN         NaN   
11503                                   NaN         NaN   
11504                                   NaN         NaN   
11505                                   NaN         NaN   
11506                                   NaN         NaN   
11507                                   NaN         NaN   
11508                                   NaN         NaN   
11509                                   NaN         NaN   
11510                                   NaN         NaN   
11511                                   NaN         NaN   
11512                                   NaN         NaN   
11513                                   NaN         NaN   
11514                                   NaN         NaN   
11515                                   NaN         NaN   
11516                                   NaN         NaN   
11517                                   NaN         NaN   
11518                                   NaN         NaN   
11519                                   NaN         NaN   
11520                                   NaN         NaN   

                                              SCH_NAME CMO_STATE  CMO_SCHNUM  \
0      ARIZONA AGRIBUSINESS & EQUINE CENTER - ESTRELLA        AZ         6.0   
1      ARIZONA AGRIBUSINESS & EQUINE CENTER - ESTRELLA        AZ         6.0   
2                                   AAEC - SMCC CAMPUS        AZ         6.0   
3                                   AAEC - SMCC CAMPUS  

In [5]:
parsed_df_6 = pd.read_csv(folder_prefix + "nowdata/parsing/parsed_df_6.csv", sep="\t", low_memory=False, encoding="utf-8")

In [6]:
parsed_df_5 = pd.read_csv(folder_prefix + "nowdata/parsing/parsed_df_5.csv", sep="\t", low_memory=False, encoding="utf-8")

In [7]:
parsed_df_4 = pd.read_csv(folder_prefix + "nowdata/parsing/parsed_df_4.csv", sep="\t", low_memory=False, encoding="utf-8")

In [8]:
parsed_df_3 = pd.read_csv(folder_prefix + "nowdata/parsing/parsed_df_3.csv", sep="\t", low_memory=False, encoding="utf-8")

In [9]:
parsed_df_2 = pd.read_csv(folder_prefix + "nowdata/parsing/parsed_df_2.csv", sep="\t", low_memory=False, encoding="utf-8")

In [10]:
parsed_df_1 = pd.read_csv(folder_prefix + 'nowdata/parsing/parsed_df_1.tar.gz', compression='gzip', sep='\t', low_memory=False, encoding="utf-8")


In [11]:
lookup = pd.DataFrame(columns=['NCESSCH','OVERLAPS_REMOVED','DATA_SOURCE'])

In [12]:
for i in parsed_df_1.columns:
    
    print(i)
    



parsed_df_1.csv
CMO_MEMSUM
SCH_NAME
CMO_STATE
CMO_SCHNUM
CMO_URL
CMO_NUMSTATES
CMO_ALLSTATES
CMO_SECTOR
CMO_NUMSTUDENTS_CREDO17
CMO_TYPE
CMO_WEBTEXT
SURVYEAR
FIPST
STABR
SEANAME
LEAID
ST_LEAID
SCHID
ST_SCHID
NCESSCH
MSTREET1
MSTREET2
MSTREET3
MCITY
MSTATE
MZIP
MZIP4
PHONE
LSTREET1
LSTREET2
LSTREET3
LCITY
LSTATE
LZIP
LZIP4
UNION
OUT_OF_STATE_FLAG
SCH_TYPE_TEXT
SCH_TYPE
RECON_STATUS
GSLO
GSHI
LEVEL
VIRTUAL
BIES
SY_STATUS_TEXT
SY_STATUS
UPDATED_STATUS_TEXT
UPDATED_STATUS
EFFECTIVE_DATE
CHARTER_TEXT
G13OFFERED
AEOFFERED
UGOFFERED
NOGRADES
CHARTAUTH1
CHARTAUTHN1
CHARTAUTH2
CHARTAUTHN2
IGOFFERED
WEBSITE
FRELCH
REDLCH
AE
TOTAL
AM
AMALM
AMALF
AS
ASALM
ASALF
HI
HIALM
HIALF
BL
BLALM
BLALF
WH
WHALM
WHALF
HP
HPALM
HPALF
TR
TRALM
TRALF
TITLEI_TEXT
TITLEI_STATUS
STITLEI
SHARED_TIME
MAGNET_TEXT
NSLPSTATUS_TEXT
NSLPSTATUS_CODE
NAME
OPSTFIPS
LSTREE
STFIP15
CNTY15
NMCNTY15
LOCALE15
LAT1516
LON1516
CBSA15
NMCBSA15
CBSATYPE15
CSA15
NMCSA15
NECTA15
NMNECTA15
CD15
SLDL15
SLDU15
LSTREET114
LSTREET214
LSTREET

In [26]:
parsed_df_6['NCESSCH'].isna().sum()

0

In [58]:
df_6_ids = list(set(parsed_df_6['NCESSCH']))
df_6_ids

[480023709189.0,
 120129004043.0,
 120129004044.0,
 120108007441.0,
 120132007956.0,
 40061403158.0,
 290060103194.0,
 50007401501.0,
 120132003875.0,
 120123003429.0,
 120108007463.0,
 69103513640.0,
 220117000234.0,
 120108008490.0,
 120108007470.0,
 480002508343.0,
 120108004926.0,
 63441012800.0,
 120108004929.0,
 50005501508.0,
 120108004933.0,
 40061302861.0,
 120105003597.0,
 480027213391.0,
 61495011927.0,
 80426001505.0,
 50005500513.0,
 480023712866.0,
 120126008427.0,
 480023712366.0,
 80002002033.0,
 480023712372.0,
 120108003956.0,
 61495010422.0,
 120108008062.0,
 63023010431.0,
 450390101639.0,
 110007200405.0,
 120126004387.0,
 370041803428.0,
 120159001775.0,
 220117000880.0,
 50006100658.0,
 480026613428.0,
 110006000310.0,
 480007111352.0,
 120126007489.0,
 110005300428.0,
 120123008208.0,
 290059903197.0,
 220117000926.0,
 40015701728.0,
 120105001702.0,
 110005300455.0,
 40024402153.0,
 480023711465.0,
 69103511792.0,
 470318002423.0,
 110005100301.0,
 120132007698

In [61]:
c=0
for i in df_6_ids:
    if i in list(so_far):
        c+=1
    
c

99

In [60]:
so_far = parsed_df_1['NCESSCH'].append(parsed_df_2['NCESSCH']).append(parsed_df_3['NCESSCH']).append(parsed_df_4['NCESSCH']).append(parsed_df_5['NCESSCH']).append(parsed_df_6['NCESSCH'])

In [62]:
so_far_unique = list(set(so_far))

In [63]:
len(so_far_unique)

6136

In [64]:
len(so_far)

6579

In [65]:
cleaned_list = [x for x in so_far_unique if str(x) != 'nan']


In [66]:
len(cleaned_list) # true unique ids that have been seen already

6135

In [67]:
parsed_df_1.shape[0]+parsed_df_2.shape[0]+parsed_df_3.shape[0]+parsed_df_4.shape[0]+parsed_df_5.shape[0]+parsed_df_6.shape[0]

6579

In [68]:
lookup['NCESSCH'] = full_250_df['NCESSCH']

In [69]:
count = 0
minus = 0
u = set(full_250_df['NCESSCH'])
for nc in u:
    indices = lookup.index[lookup['NCESSCH'] == nc].tolist()
    if nc in cleaned_list: #if already parsed 
        for i in indices:
            lookup.loc[i, 'OVERLAPS_REMOVED'] = 1
            if nc in df_6_ids:
                lookup.loc[i, 'DATA_SOURCE'] = 'full_15_250'
            else :
                lookup.loc[i, 'DATA_SOURCE'] = 'full'
        count+=1
    else:
        
        for i in indices:
            lookup.loc[i, 'OVERLAPS_REMOVED'] = 0
            lookup.loc[i, 'DATA_SOURCE'] = 'full_15_250'
        minus+=1
        
        
        

In [70]:
count

6135

In [71]:
minus

4830

In [72]:
count+minus

10965

In [74]:
six = lookup[(lookup['DATA_SOURCE'] == 'full_15_250') & (lookup['OVERLAPS_REMOVED'] == 1)]

In [75]:
len(set(six['NCESSCH']))

99

In [76]:
lookup.shape[0]

11521

In [78]:
lookup[lookup['OVERLAPS_REMOVED'] == 1].shape[0] #this number is bigger than len(cleaned_list) cz lookup has repeated rows
#count is 6036 which means it made 1, 6036 times -> which is the leangth of cleaned list


6347

In [79]:
len(so_far)

6579

In [80]:
lookup.isna().sum()

NCESSCH             0
OVERLAPS_REMOVED    0
DATA_SOURCE         0
dtype: int64

In [81]:
len(set(so_far))

6136

In [82]:
lookup.to_csv(folder_prefix + "/nowdata/parsing/lookup.csv", mode="w", index=False, header=lookup.columns.values, sep="\t", encoding="utf-8")

In [83]:
s = pd.read_csv(folder_prefix + "/nowdata/parsing/lookup.csv", sep="\t", low_memory=False, encoding="utf-8")

In [84]:
s

NCESSCH  OVERLAPS_REMOVED  DATA_SOURCE
0      4.008280e+10                 0  full_15_250
1      4.008280e+10                 0  full_15_250
2      4.004170e+10                 0  full_15_250
3      4.004170e+10                 0  full_15_250
4      4.001060e+10                 0  full_15_250
5      4.001060e+10                 0  full_15_250
6      4.800034e+11                 1         full
7      4.800034e+11                 1         full
8      4.800034e+11                 1         full
9      4.800192e+11                 1         full
10     4.800192e+11                 1         full
11     4.800192e+11                 1         full
12     4.800192e+11                 1         full
13     6.118201e+10                 1         full
14     6.910351e+10                 1         full
15     6.345901e+10                 1         full
16     6.143701e+10                 1         full
17     4.800019e+11                 1         full
18     4.800019e+11                 1         full
19     4.800158e+11                 1         full
20     4.800158e+11                 1         full
21     4.800158e+11                 1         full
22     4.200813e+11                 1         full
23     4.200813e+11                 1         full
24     4.200835e+11                 1         full
25     4.200835e+11                 1         full
26     4.200843e+11                 1         full
27     4.200839e+11                 0  full_15_250
28     4.200043e+11                 0  full_15_250
29     1.200180e+11                 0  full_15_250
...             ...               ...          ...
11491  4.700148e+11                 1         full
11492  4.703180e+11                 1         full
11493  4.800071e+11                 1         full
11494  4.800074e+11                 1         full
11495  4.800179e+11                 1         full
11496  4.800186e+11                 1         full
11497  4.800195e+11                 1         full
11498  4.800258e+11                 1         full
11499  4.800283e+11                 1         full
11500  4.800283e+11                 1         full
11501  4.801400e+11                 1         full
11502  4.801420e+11                 1         full
11503  4.801421e+11                 1         full
11504  4.801449e+11                 1         full
11505  4.801451e+11                 1         full
11506  4.801456e+11                 1         full
11507  4.801457e+11                 1         full
11508  4.801458e+11                 1         full
11509  4.823640e+11                 1         full
11510  4.823640e+11                 1         full
11511  4.823640e+11                 1         full
11512  4.825260e+11                 1         full
11513  4.834050e+11                 1         full
11514  4.900162e+11                 1         full
11515  4.900174e+11                 1         full
11516  4.900197e+11                 1         full
11517  5.509600e+11                 1         full
11518  5.509600e+11                 1         full
11519  5.509600e+11                 1         full
11520  5.601980e+11                 1         full

[11521 rows x 3 columns]

In [85]:
s[s['OVERLAPS_REMOVED'] == 1].shape[0]

6347

In [86]:
s.isna().sum()

NCESSCH             0
OVERLAPS_REMOVED    0
DATA_SOURCE         0
dtype: int64

In [87]:
unseen = s[s['OVERLAPS_REMOVED'] == 0]
unseen

NCESSCH  OVERLAPS_REMOVED  DATA_SOURCE
0      4.008280e+10                 0  full_15_250
1      4.008280e+10                 0  full_15_250
2      4.004170e+10                 0  full_15_250
3      4.004170e+10                 0  full_15_250
4      4.001060e+10                 0  full_15_250
5      4.001060e+10                 0  full_15_250
27     4.200839e+11                 0  full_15_250
28     4.200043e+11                 0  full_15_250
29     1.200180e+11                 0  full_15_250
30     1.200180e+11                 0  full_15_250
31     1.201320e+11                 0  full_15_250
32     1.201320e+11                 0  full_15_250
33     1.200180e+11                 0  full_15_250
34     1.200180e+11                 0  full_15_250
35     1.200480e+11                 0  full_15_250
36     1.200480e+11                 0  full_15_250
37     1.200480e+11                 0  full_15_250
38     1.200480e+11                 0  full_15_250
39     1.200180e+11                 0  full_15_250
40     1.200180e+11                 0  full_15_250
41     1.200180e+11                 0  full_15_250
42     1.200180e+11                 0  full_15_250
43     1.200180e+11                 0  full_15_250
44     1.200390e+11                 0  full_15_250
45     1.200390e+11                 0  full_15_250
46     1.200390e+11                 0  full_15_250
47     1.200390e+11                 0  full_15_250
48     1.200390e+11                 0  full_15_250
49     1.200390e+11                 0  full_15_250
50     1.200390e+11                 0  full_15_250
...             ...               ...          ...
8367   1.201230e+11                 0  full_15_250
9453   2.900602e+11                 0  full_15_250
9454   2.900603e+11                 0  full_15_250
9455   2.900604e+11                 0  full_15_250
9456   2.900606e+11                 0  full_15_250
9457   2.900608e+11                 0  full_15_250
9458   2.900609e+11                 0  full_15_250
9459   2.900611e+11                 0  full_15_250
9460   2.900613e+11                 0  full_15_250
9461   3.901416e+11                 0  full_15_250
9462   3.200001e+11                 0  full_15_250
11184  5.515360e+11                 0  full_15_250
11185  5.515360e+11                 0  full_15_250
11186  5.515750e+11                 0  full_15_250
11187  5.515780e+11                 0  full_15_250
11188  5.515780e+11                 0  full_15_250
11189  5.515780e+11                 0  full_15_250
11190  5.515780e+11                 0  full_15_250
11208  7.200030e+11                 0  full_15_250
11209  7.200030e+11                 0  full_15_250
11210  7.200030e+11                 0  full_15_250
11211  7.200030e+11                 0  full_15_250
11212  7.200030e+11                 0  full_15_250
11213  7.200030e+11                 0  full_15_250
11214  7.200030e+11                 0  full_15_250
11215  7.200030e+11                 0  full_15_250
11216  7.200030e+11                 0  full_15_250
11217  7.200030e+11                 0  full_15_250
11218  7.200030e+11                 0  full_15_250
11219  7.200030e+11                 0  full_15_250

[5174 rows x 3 columns]

In [88]:
5279 + 6242



11521

In [89]:
li = list(unseen['NCESSCH'])

In [90]:
len(li)

5174

In [91]:
p = full_250_df[full_250_df['NCESSCH'].isin(li)]

In [92]:
p

CMO_NAME  CMO_MEMSUM  \
0                                      AAEC      1320.0   
1      Arizona Agribusiness & Equine Center      1320.0   
2                                      AAEC      1320.0   
3      Arizona Agribusiness & Equine Center      1320.0   
4                                      AAEC      1320.0   
5      Arizona Agribusiness & Equine Center      1320.0   
27                             ASPIRA of PA      3966.0   
28                             ASPIRA of PA      3966.0   
29                                Academica     48541.0   
30                         Somerset Academy     23411.0   
31                                Academica     48541.0   
32                         Somerset Academy     23411.0   
33                                Academica     48541.0   
34                         Somerset Academy     23411.0   
35                                Academica     48541.0   
36                         Somerset Academy     23411.0   
37                                Academica     48541.0   
38                         Somerset Academy     23411.0   
39                                Academica     48541.0   
40                         Somerset Academy     23411.0   
41                                Academica     48541.0   
42                         Somerset Academy     23411.0   
43                         Somerset Academy     23411.0   
44                                Academica     48541.0   
45                         Somerset Academy     23411.0   
46                                Academica     48541.0   
47                         Somerset Academy     23411.0   
48                         Somerset Academy     23411.0   
49                                Academica     48541.0   
50                         Somerset Academy     23411.0   
...                                     ...         ...   
8367                                    NaN         NaN   
9453                                    NaN         NaN   
9454                                    NaN         NaN   
9455                                    NaN         NaN   
9456                                    NaN         NaN   
9457                                    NaN         NaN   
9458                                    NaN         NaN   
9459                                    NaN         NaN   
9460                                    NaN         NaN   
9461                                    NaN         NaN   
9462                                    NaN         NaN   
11184                                   NaN         NaN   
11185                                   NaN         NaN   
11186                                   NaN         NaN   
11187                                   NaN         NaN   
11188                                   NaN         NaN   
11189                                   NaN         NaN   
11190                                   NaN         NaN   
11208                                   NaN         NaN   
11209                                   NaN         NaN   
11210                                   NaN         NaN   
11211                                   NaN         NaN   
11212                                   NaN         NaN   
11213                                   NaN         NaN   
11214                                   NaN         NaN   
11215                                   NaN         NaN   
11216                                   NaN         NaN   
11217                                   NaN         NaN   
11218                                   NaN         NaN   
11219                                   NaN         NaN   

                                                SCH_NAME CMO_STATE  \
0        ARIZONA AGRIBUSINESS & EQUINE CENTER - ESTRELLA        AZ   
1        ARIZONA AGRIBUSINESS & EQUINE CENTER - ESTRELLA        AZ   
2                                     AAEC - SMCC CAMPUS        AZ   
3                                     AAEC - SMCC CAMPUS        AZ   
4                         

In [160]:
new_data = pd.DataFrame(columns=['id', 'name'])
new_data['id'] = pd.Series([[100], [109], [40], [32], [16], [19], [8], [33], [20], [21], [54], [3]])
new_data['name'] = pd.Series(["Billy", "Krutika", "Joe", "fdjs", "gfd", "re","fde", "t", "a", "e", "bf", "tr"])
# i = new_data.head(2)
# new_data = new_data.append(i)
new_data

id     name
0   [100]    Billy
1   [109]  Krutika
2    [40]      Joe
3    [32]     fdjs
4    [16]      gfd
5    [19]       re
6     [8]      fde
7    [33]        t
8    [20]        a
9    [21]        e
10   [54]       bf
11    [3]       tr

In [111]:
arr_of_dfs = np.array_split(new_data, len(new_data['id']))


In [112]:
[ x + 1 for x in [0,1] ]


[1, 2]

In [126]:
def add_val(li):
    print("hi")
    return [x + 1 for x in li ]

In [127]:
def parse_df(old_list):
    new_list = add_val(old_list)
    return new_list

In [153]:
def chunk_assign(df_chunk): #Jaren chunk by chunk 
    global num
    #global temp_df
    global temp_df
    
    #already_cleaned_chunk = df_chunk.loc[df_chunk['OVERLAPS_REMOVED'] == 1] don't do anything with this
    
    df_chunk['id'] = df_chunk['id'].apply(parse_df)
    
    temp_df = temp_df.append(df_chunk, ignore_index = True)
    print(temp_df['id'].values)

    
    
            
    if num == 0: # Save first slice to new file (overwriting if needed)
        temp_df.to_csv(folder_prefix + "nowdata/parsing/temp_test.csv", mode="w", index=False, header=df_chunk.columns.values, sep="\t", encoding="utf-8")
        
    elif (num > 0) and (num % 10 == 0):
        temp_df.to_csv(folder_prefix + "nowdata/parsing/temp_test.csv", mode="a", index=False, header=False, sep="\t", encoding="utf-8")


    num+=1
    
    return df_chunk

In [156]:
num = 0
temp_df = pd.DataFrame(columns=new_data.columns)
numcpus = len(os.sched_getaffinity(0)) # Detect and assign number of available CPUs
p = mp.Pool(numcpus)
c = 0
j = p.map(chunk_assign, arr_of_dfs)

hi
hi
hi
hi
hi
[list([41])]
[list([33])]
hi
hi
[list([9])]
[list([17])]
hi
hi
[list([101])]
hi
hi
hi
[list([34])]
[list([110])]
[list([21])]
[list([22])]
[list([20])]
[list([55])]
[list([4])]


In [157]:
j

[      id   name
 0  [101]  Billy,       id     name
 1  [110]  Krutika,      id name
 2  [41]  Joe,      id  name
 3  [33]  fdjs,      id name
 4  [17]  gfd,      id name
 5  [20]   re,     id name
 6  [9]  fde,      id name
 7  [34]    t,      id name
 8  [21]    a,      id name
 9  [22]    e,       id name
 10  [55]   bf,      id name
 11  [4]   tr]

In [125]:
arr_of_dfs

[      id   name
 0  [100]  Billy,       id     name
 1  [109]  Krutika,      id name
 2  [40]  Joe,      id  name
 3  [32]  fdjs,      id name
 4  [16]  gfd,      id name
 5  [19]   re,     id name
 6  [8]  fde,      id name
 7  [33]    t,      id name
 8  [20]    a,      id name
 9  [21]    e,       id name
 10  [54]   bf,      id name
 11  [3]   tr]

In [149]:
t = pd.read_csv(folder_prefix + "nowdata/parsing/temp_test.csv", sep="\t", low_memory=False, encoding="utf-8")

In [150]:
t

id name
0  [55]   bf

In [7]:
full_250_df = pd.read_csv(folder_prefix + "nowdata/parsing/parsed_df_2.csv", sep="\t", low_memory=False, encoding="utf-8")


In [8]:
arr_of_dfs = np.array_split(full_250_df, len(full_250_df['WEBTEXT']))

In [9]:
full_250_df.shape[0]

154

In [10]:
len(arr_of_dfs)

154

In [11]:
arr_of_dfs

[              CMO_NAME  CMO_MEMSUM            SCH_NAME CMO_STATE  CMO_SCHNUM  \
 0  IDEA Public Schools     23807.0  IDEA ACADEMY ALAMO        TX        61.0   
 
                               CMO_URL  CMO_NUMSTATES CMO_ALLSTATES CMO_SECTOR  \
 0  https://www.ideapublicschools.org/            1.0            TX        CMO   
 
    CMO_NUMSTUDENTS_CREDO17       ...        YEAR_OPENED YEAR_CLOSED  \
 0                  17020.0       ...             2010.0         NaN   
 
                                             SEARCH16  TOTETH    PCTETH  AGE  \
 0  IDEA ACADEMY ALAMO  325 E SH 495 , ALAMO TX 78...   814.0  0.991474  5.0   
 
      PCTFRL   PLACE        STR OVERLAPS_REMOVED  
 0  0.691839  Suburb  42.059426                1  
 
 [1 rows x 392 columns],
                                   CMO_NAME  CMO_MEMSUM  \
 1  International Leadership Of Texas (ILT)      5030.0   
 
                                            SCH_NAME CMO_STATE  CMO_SCHNUM  \
 1  INTERNATIONAL LEADERSHIP OF TEX

In [14]:
k = [1,3]
k.append([6,9])
k


[1, 3, [6, 9]]

In [18]:
ten_count = int(round(len(arr_of_dfs) /10))
ten_count

15

In [21]:
indices_arr = np.arange(len(arr_of_dfs))
ind_sublists = np.array_split(indices_arr, ten_count)


In [22]:
ind_sublists

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
 array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]),
 array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]),
 array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53]),
 array([54, 55, 56, 57, 58, 59, 60, 61, 62, 63]),
 array([64, 65, 66, 67, 68, 69, 70, 71, 72, 73]),
 array([74, 75, 76, 77, 78, 79, 80, 81, 82, 83]),
 array([84, 85, 86, 87, 88, 89, 90, 91, 92, 93]),
 array([ 94,  95,  96,  97,  98,  99, 100, 101, 102, 103]),
 array([104, 105, 106, 107, 108, 109, 110, 111, 112, 113]),
 array([114, 115, 116, 117, 118, 119, 120, 121, 122, 123]),
 array([124, 125, 126, 127, 128, 129, 130, 131, 132, 133]),
 array([134, 135, 136, 137, 138, 139, 140, 141, 142, 143]),
 array([144, 145, 146, 147, 148, 149, 150, 151, 152, 153])]

In [24]:
for i in ind_sublists :
    print(type(i))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [28]:
len(arr_of_dfs)

154

In [34]:
ind_sublists[1][0]

11

In [35]:
ind_sublists[1][len(ind_sublists[1]) - 1]

21

In [38]:
len(arr_of_dfs[ind_sublists[0][0]: ind_sublists[0][len(ind_sublists[0]) - 1] + 1])

11

In [41]:
arr_of_dfs[ind_sublists[1][0]: ind_sublists[1][len(ind_sublists[1]) -1] +1]

[   CMO_NAME  CMO_MEMSUM                SCH_NAME CMO_STATE  CMO_SCHNUM  \
 11    Icahn      1926.0  ICAHN CHARTER SCHOOL 3        NY         7.0   
 
                                 CMO_URL  CMO_NUMSTATES CMO_ALLSTATES  \
 11  http://www.icahncharterschools.org/            1.0            NY   
 
    CMO_SECTOR  CMO_NUMSTUDENTS_CREDO17       ...        YEAR_OPENED  \
 11        NaN                      NaN       ...             2008.0   
 
    YEAR_CLOSED                                           SEARCH16  TOTETH  \
 11         NaN  ICAHN CHARTER SCHOOL 3  1500 PELHAM PKWY S , B...   306.0   
 
       PCTETH  AGE    PCTFRL PLACE        STR OVERLAPS_REMOVED  
 11  0.968354  7.0  0.816456  City  15.047619                1  
 
 [1 rows x 392 columns],
    CMO_NAME  CMO_MEMSUM                SCH_NAME CMO_STATE  CMO_SCHNUM  \
 12    Icahn      1926.0  ICAHN CHARTER SCHOOL 4        NY         7.0   
 
                                 CMO_URL  CMO_NUMSTATES CMO_ALLSTATES  \
 12  http://www.ic

In [45]:
for sub_array in ind_sublists:
    arr_dfs_chunk = arr_of_dfs[sub_array[0]: sub_array[len(sub_array) -1] +1]
    print(str(sub_array[0]) + " : " + str(sub_array[len(sub_array) -1]))

0 : 10
11 : 21
22 : 32
33 : 43
44 : 53
54 : 63
64 : 73
74 : 83
84 : 93
94 : 103
104 : 113
114 : 123
124 : 133
134 : 143
144 : 153


In [46]:
ind_sublists

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
 array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]),
 array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]),
 array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53]),
 array([54, 55, 56, 57, 58, 59, 60, 61, 62, 63]),
 array([64, 65, 66, 67, 68, 69, 70, 71, 72, 73]),
 array([74, 75, 76, 77, 78, 79, 80, 81, 82, 83]),
 array([84, 85, 86, 87, 88, 89, 90, 91, 92, 93]),
 array([ 94,  95,  96,  97,  98,  99, 100, 101, 102, 103]),
 array([104, 105, 106, 107, 108, 109, 110, 111, 112, 113]),
 array([114, 115, 116, 117, 118, 119, 120, 121, 122, 123]),
 array([124, 125, 126, 127, 128, 129, 130, 131, 132, 133]),
 array([134, 135, 136, 137, 138, 139, 140, 141, 142, 143]),
 array([144, 145, 146, 147, 148, 149, 150, 151, 152, 153])]